# Generated by Django 5.1 on 2024-08-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('num_amount', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('amount_type', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_currency', models.CharField(max_length=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_currency', models.CharField(max_length=10)),
                ('expiration_date', models.DateField()),
                ('deliver_date', models.DateField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки продуктов',
            },
        ),
    ]
