# Generated by Django 5.1 on 2024-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=255, unique=True)),
                ('add', models.BooleanField(default=False)),
                ('sell', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('see_cost_price', models.BooleanField(default=False)),
                ('see_sell_price', models.BooleanField(default=False)),
                ('see_amount', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки доступа сотрудникам',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('num_amount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('access', models.ManyToManyField(related_name='warehouses', to='warehouse.permission')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки склада',
            },
        ),
    ]
