# Generated by Django 5.1 on 2024-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('data', models.TextField()),
                ('image', models.ImageField(upload_to='notifications/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки уведомдений',
            },
        ),
    ]
