# Generated by Django 5.1 on 2024-08-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProduct',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('amount_type', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_currency', models.CharField(max_length=10)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настрйки истории продукта',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_return_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='histories', to='history.historyproduct')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки истории пользователя',
            },
        ),
    ]
